server:
  port: 8900
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: MyZuul
    #zuul实现路由转发的作用
zuul:
  routes: #路由
    hello: #随便命名
      path: /tina/** #随意命名 但是需要符合格式 外界的访问路径
      service-id: tina-consumer  # 服务的名称 一般都是指向的消费者
